# Generated by Django 5.1.1 on 2024-09-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_category_options_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
