# Generated by Django 5.1.1 on 2024-09-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_pokemon_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
