# Generated by Django 5.1.1 on 2024-09-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_pokemon_unique_id_alter_pokemon_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
