# Generated by Django 5.1.1 on 2024-09-23 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_rarity_options_pokemon_rarity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='owner',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_pokemons', to='item.category'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_pokemons', to='item.generation'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_pokemons', to='item.rarity'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_pokemons', to='item.region'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='original_pokemons', to='item.type'),
        ),
        migrations.CreateModel(
            name='PokemonOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_original', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('current_experience', models.IntegerField(default=0)),
                ('is_tradeable', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pokemon_images')),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pokemons', to='item.category')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pokemons', to='item.generation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pokemons', to=settings.AUTH_USER_MODEL)),
                ('rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pokemons', to='item.rarity')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pokemons', to='item.region')),
                ('types', models.ManyToManyField(blank=True, related_name='user_pokemons', to='item.type')),
            ],
        ),
    ]
