# Generated by Django 5.1.1 on 2024-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_pokemon_owner_alter_pokemon_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarity',
            name='level_cap',
            field=models.IntegerField(default=20),
        ),
    ]
