# Generated by Django 5.1.1 on 2024-09-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_rarity_level_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarity',
            name='required_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
