# Generated by Django 5.1.1 on 2024-09-26 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_bug_tokens_userprofile_dark_tokens_and_more'),
        ('item', '0011_rarity_required_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonofuser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pokemons', to='core.userprofile'),
        ),
    ]
