# Generated by Django 5.1.1 on 2024-09-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_pokemonofuser_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonofuser',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
