# Generated by Django 5.1.1 on 2024-09-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_pokemonofuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonofuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images'),
        ),
    ]
