# Generated by Django 5.1.1 on 2024-10-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_pokemonofuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonofuser',
            name='model_directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
