# Generated by Django 5.1.1 on 2024-10-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_pokemonofuser_model_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonofuser',
            name='model_file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
