# Generated by Django 5.1.1 on 2024-09-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_bug_tokens_userprofile_dark_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
