# Generated by Django 5.1.1 on 2024-09-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_last_claimed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_claimed',
            new_name='last_claimed_pokepesos',
        ),
    ]
