# Generated by Django 5.1.1 on 2024-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_last_claimed_userprofile_last_claimed_pokepesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
